import { EXPO_SUPABASE_URL, EXPO_SUPABASE_API_KEY } from "@env";

const SUPABASE_URL = EXPO_SUPABASE_URL || "";
const SUPABASE_API_KEY = EXPO_SUPABASE_API_KEY || "";

export { SUPABASE_URL, SUPABASE_API_KEY };
